### PR TITLE
Simplified

### PR DESCRIPTION
**Pull request by richelbilderbeek**
It is common that the first part of the function checks the input. `stop` should be used to signal incorrect function arguments. And it saves you two indentation levels for the rest of the (huge) function.

Functionality should still be intact, but without tests you can never be sure.

### CODE REVIEW

**Comment by richelbilderbeek** [comment]
Perhaps you are unaware: click on 'Merge' to merge my suggestions with your code. Click 'Close' to ignore my suggestion.

I see there are merge conflicts now. They are easy to fix, but I cannot do so myself without proper access rights.

**Comment by xl0418** [comment]
Hi Richel:

     Thanks! I am trying to reuse Github since I want to program both on Windows and OSX. I don’t know if this reply will reach you. Let me have a try.

Best,

Liang
-- 
Liang Xu
PhD Student
Theoretical Research in Evolutionary Life Sciences (TRÊS)
Groningen Institute for Evolutionary Life Sciences
Box 11103
9700 CC Groningen

发件人: Richel Bilderbeek
发送时间: Wednesday, January 31, 2018 8:37 AM
收件人: xl0418/SDDD
抄送: Subscribed
主题: Re: [xl0418/SDDD] Simplified (#1)

Perhaps you are unaware: click on 'Merge' to merge my suggestions with your code. Click 'Close' to ignore my suggestion.
I see there are merge conflicts now. They are easy to fix, but I cannot do so myself without proper access rights.

**Comment by richelbilderbeek** [comment]
GitHub messages reach me just fine :-)

**Review by xl0418 — COMMENTED** [review]
Accept changes.

**Comment by richelbilderbeek** [comment]
See [here](https://help.github.com/articles/merging-a-pull-request) and [here](https://differential.com/insights/best-way-to-merge-a-github-pull-request) for articles how to merge a pull request. 

Spoiler: click on the green button with label 'Merge Pull Request'.

**Comment by xl0418** [comment]
Oh, I know why I couldn’t find merge button. There is a conflict in this branch. I have no idea how to solve it. 

<<<<<<< master
/home/richel/GitHubs/SDDD/R/Simdata.R="397E2633"
/home/richel/GitHubs/SDDD/R/sddsim.R="E10ADE3E"
=======
C:/Liang/Googlebox/R/Project2/plotstepfun.R="95E9F9D0"
>>>>>>> master
C:/Liang/Googlebox/Research/Project1/R_pro1/Final/SDDD/R/Nindex.R="DB17FEA8"
C:/Liang/Googlebox/Research/Project1/R_pro1/Final/SDDD/R/event_matrix.R="90327C5"
C:/Liang/Googlebox/Research/Project1/R_pro1/Final/SDDD/R/sddsim.R="90F8E9C4"
C:/Liang/Googlebox/Research/Project1/R_pro1/Final/SDDD/R/simpackage.R="D813A8A5"
C:/Liang/Googlebox/Research/Project1/R_pro1/Final/sddsim-d.R="AF59DA27"


Best,

Liang
-- 
Liang Xu
PhD Student
Theoretical Research in Evolutionary Life Sciences (TRÊS)
Groningen Institute for Evolutionary Life Sciences
Box 11103
9700 CC Groningen

发件人: Richel Bilderbeek
发送时间: Friday, February 2, 2018 4:58 PM
收件人: xl0418/SDDD
抄送: Liang Xu; Comment
主题: Re: [xl0418/SDDD] Simplified (#1)

See here and here for articles how to merge a pull request.
Spoiler: click on the green button with label 'Merge Pull Request'.

**Comment by xl0418** [comment]
Haha, thanks! I did want to merge but couldn’t find how. 

Best,

Liang
-- 
Liang Xu
PhD Student
Theoretical Research in Evolutionary Life Sciences (TRÊS)
Groningen Institute for Evolutionary Life Sciences
Box 11103
9700 CC Groningen

发件人: Richel Bilderbeek
发送时间: Friday, February 2, 2018 4:58 PM
收件人: xl0418/SDDD
抄送: Liang Xu; Comment
主题: Re: [xl0418/SDDD] Simplified (#1)

See here and here for articles how to merge a pull request.
Spoiler: click on the green button with label 'Merge Pull Request'.

**Pull request merged**
